version: "3.8"

services:

  config:
    image: eccsm/config:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - eccsm
   
  eurekaserver:
    image: eccsm/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - eccsm
    depends_on:
      - config
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      
  minicommerce:
    image: eccsm/minicommerce:latest
    network_mode: host
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - eccsm
    depends_on:
      - config
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
  
  orders:
    image: eccsm/orderservice:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - eccsm
    depends_on:
      - config
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
  products:
    image: eccsm/productservice:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - eccsm
    depends_on:
      - config
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  customers:
    image: eccsm/customerservice:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - eccsm
    depends_on:
      - config
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/


  gatewayserver:
    image: eccsm/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - eccsm
    depends_on:
      - config
      - eurekaserver
      - minicommerce
      - products
      - customers
      - orders

    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      
networks:
  eazybank: